export const YELLOW = '#05f' //'#465fdd'
export const RED = '#a30100'
export const WHITE = '#fff'
export const BLACK = '#000'
export const PURPLE = '#50f'
export const BLUE = '#05f'
export const NUBLUE = '#386bd7'
